CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255),
    enabled BOOL NOT NULL DEFAULT false,
    created DATETIME DEFAULT NULL,
    modified DATETIME DEFAULT NULL,
    last_login DATETIME DEFAULT NULL
);  


CREATE TABLE campaigns (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    chaos INT NOT NULL DEFAULT 5
);

CREATE TABLE scenes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    order FLOAT UNIQUE NOT NULL
);

CREATE TABLE blocks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order FLOAT UNIQUE NOT NULL
);


