version: '3.1'
services:
  sologm-mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: sologm-mailhog
    ports:
      - "8125:8025"

  sologm-mysql:
    image: 'mysql:8.0'
    container_name: sologm-mysql
    working_dir: /var/www/sologm
    volumes:
        - ../mysql:/var/lib/mysql
        - ../mysql-files:/var/lib/mysql-files
        - ../cakephp:/var/www/sologm
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "8106:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  sologm-nginx:
    image: 'nginx:alpine'
    container_name: sologm-nginx
    working_dir: /var/www/sologm
    volumes:
        - ../cakephp:/var/www/sologm
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "8180:80"
    links:
     - sologm-php-fpm

  sologm-php-fpm:
    build: ./php-fpm
    container_name: sologm-php-fpm
    working_dir: /var/www/sologm
    volumes:
      - ../cakephp:/var/www/sologm
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    links:
      - sologm-mailhog
      - sologm-mysql
